// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9ygJ_H58VBS-kF87Dw04RZWNV0ZYXtQ',
    appId: '1:707631703569:web:7b7a3df2d3399ed682b3b0',
    messagingSenderId: '707631703569',
    projectId: 'qr-app-ieee-nu',
    authDomain: 'qr-app-ieee-nu.firebaseapp.com',
    databaseURL: 'https://qr-app-ieee-nu-default-rtdb.firebaseio.com',
    storageBucket: 'qr-app-ieee-nu.appspot.com',
    measurementId: 'G-7QBD4NYT69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbs1C9LQHxD9YoVJqgaWqFhWMpaGhJInk',
    appId: '1:707631703569:android:b3ceca6791748f0382b3b0',
    messagingSenderId: '707631703569',
    projectId: 'qr-app-ieee-nu',
    databaseURL: 'https://qr-app-ieee-nu-default-rtdb.firebaseio.com',
    storageBucket: 'qr-app-ieee-nu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClV5nLLplhJU2jbwMfeutp8lEC2ELlGtY',
    appId: '1:707631703569:ios:8029e06a8a9f7dba82b3b0',
    messagingSenderId: '707631703569',
    projectId: 'qr-app-ieee-nu',
    databaseURL: 'https://qr-app-ieee-nu-default-rtdb.firebaseio.com',
    storageBucket: 'qr-app-ieee-nu.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClV5nLLplhJU2jbwMfeutp8lEC2ELlGtY',
    appId: '1:707631703569:ios:e81aa459819c302e82b3b0',
    messagingSenderId: '707631703569',
    projectId: 'qr-app-ieee-nu',
    databaseURL: 'https://qr-app-ieee-nu-default-rtdb.firebaseio.com',
    storageBucket: 'qr-app-ieee-nu.appspot.com',
    iosBundleId: 'com.example.qrScanner.RunnerTests',
  );
}
